/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TrainingRecord {
    id: RecordId;
    status: TrainingStatus;
    title: string;
    completionDate?: bigint;
    expiryDate?: bigint;
    description: string;
    employeeId: EmployeeId;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Document {
    id: DocumentId;
    title: string;
    content?: string;
    description: string;
    isVisible: boolean;
    category: DocumentCategory;
    uploadedAt: bigint;
    fileUrl?: string;
}
export interface Shift {
    id: ShiftId;
    startTime: bigint;
    endTime: bigint;
    date: bigint;
    department: string;
    assignedEmployees: Array<EmployeeId>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type RecordId = string;
export interface ShiftNote {
    id: RecordId;
    noteText: string;
    employeeId?: EmployeeId;
    createdTimestamp: bigint;
    shiftId: ShiftId;
}
export type NominationId = string;
export type EmployeeId = string;
export type ShiftId = string;
export type DocumentId = string;
export interface Employee {
    id: EmployeeId;
    role: EmployeeRole;
    fullName: string;
    isActive: boolean;
    email: string;
    jobTitle: string;
    phone: string;
    department: string;
    startDate: bigint;
    accountLevel: EmployeeRole;
}
export interface NominationWinner {
    month: string;
    hasReceivedBonus: boolean;
    employeeId: EmployeeId;
}
export interface HolidayRequest {
    id: HolidayRequestId;
    status: HolidayRequestStatus;
    endDate: bigint;
    createdAt: bigint;
    employeeId: EmployeeId;
    startDate: bigint;
    reason?: string;
}
export interface ManagerNote {
    id: ManagerNoteId;
    content: string;
    createdAt: bigint;
    noteType: ManagerNoteType;
    authorEmployeeId: EmployeeId;
    employeeId: EmployeeId;
}
export type ManagerNoteId = string;
export interface AppraisalRecord {
    id: RecordId;
    scheduledDate: bigint;
    appraisalType: AppraisalType;
    employeeId: EmployeeId;
    notes: string;
    isComplete: boolean;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export type HolidayRequestId = string;
export interface SicknessRecord {
    id: RecordId;
    absenceStartDate: bigint;
    absenceEndDate: bigint;
    employeeId: EmployeeId;
    returnNote: string;
    reason: string;
}
export interface Resource {
    id: ResourceId;
    title: string;
    content: string;
    createdAt: bigint;
    isRestricted: boolean;
    category: ResourceCategory;
}
export type ResourceId = string;
export interface Nomination {
    id: NominationId;
    month: string;
    nomineeEmployeeId: EmployeeId;
    submittedAt: bigint;
    nominatorEmployeeId: EmployeeId;
    reason: string;
}
export interface UserProfile {
    name: string;
    employeeId?: EmployeeId;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AppraisalType {
    annual = "annual",
    midYear = "midYear",
    probationary = "probationary"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum DocumentCategory {
    other = "other",
    form = "form",
    handbook = "handbook",
    policy = "policy"
}
export enum EmployeeRole {
    manager = "manager",
    admin = "admin",
    employee = "employee"
}
export enum HolidayRequestStatus {
    pending = "pending",
    approved = "approved",
    declined = "declined"
}
export enum ManagerNoteType {
    concern = "concern",
    sickness = "sickness",
    performance = "performance",
    general = "general"
}
export enum ResourceCategory {
    forms = "forms",
    other = "other",
    logins = "logins",
    prices = "prices"
}
export enum TrainingStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAppraisalRecord(record: AppraisalRecord): Promise<void>;
    addDocument(document: Document): Promise<void>;
    addEmployee(employee: Employee): Promise<void>;
    addManagerNote(note: ManagerNote): Promise<void>;
    addResource(resource: Resource): Promise<void>;
    addShift(shift: Shift): Promise<void>;
    addShiftNote(note: ShiftNote): Promise<void>;
    addSicknessRecord(record: SicknessRecord): Promise<void>;
    addTrainingRecord(record: TrainingRecord): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteDocument(id: DocumentId): Promise<void>;
    deleteManagerNote(id: ManagerNoteId): Promise<void>;
    deleteResource(id: ResourceId): Promise<void>;
    deleteShift(id: ShiftId): Promise<void>;
    getAllDocuments(): Promise<Array<Document>>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAllHolidayRequests(): Promise<Array<HolidayRequest>>;
    getAllShifts(): Promise<Array<Shift>>;
    getAppraisalsByEmployee(employeeId: EmployeeId): Promise<Array<AppraisalRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmployee(id: EmployeeId): Promise<Employee | null>;
    getHolidayRequestsByEmployee(employeeId: EmployeeId): Promise<Array<HolidayRequest>>;
    getManagerNotesByEmployee(employeeId: EmployeeId): Promise<Array<ManagerNote>>;
    getNominationsByMonth(month: string): Promise<Array<Nomination>>;
    getResources(category: ResourceCategory | null): Promise<Array<Resource>>;
    getShiftNotesByShift(shiftId: ShiftId): Promise<Array<ShiftNote>>;
    getShiftsByEmployee(employeeId: EmployeeId): Promise<Array<Shift>>;
    getSicknessRecordsByEmployee(employeeId: EmployeeId): Promise<Array<SicknessRecord>>;
    getTrainingRecordsByEmployee(employeeId: EmployeeId): Promise<Array<TrainingRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWinnerByMonth(month: string): Promise<NominationWinner | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    markWinnerBonus(month: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setMonthWinner(month: string, employeeId: EmployeeId): Promise<void>;
    submitHolidayRequest(request: HolidayRequest): Promise<void>;
    submitNomination(nomination: Nomination): Promise<void>;
    updateAppraisalRecord(record: AppraisalRecord): Promise<void>;
    updateDocument(document: Document): Promise<void>;
    updateEmployee(employee: Employee): Promise<void>;
    updateHolidayRequestStatus(id: HolidayRequestId, status: HolidayRequestStatus): Promise<void>;
    updateManagerNote(note: ManagerNote): Promise<void>;
    updateResource(resource: Resource): Promise<void>;
    updateShift(shift: Shift): Promise<void>;
    updateTrainingRecord(record: TrainingRecord): Promise<void>;
}
import type { AppraisalRecord as _AppraisalRecord, AppraisalType as _AppraisalType, ApprovalStatus as _ApprovalStatus, Document as _Document, DocumentCategory as _DocumentCategory, DocumentId as _DocumentId, Employee as _Employee, EmployeeId as _EmployeeId, EmployeeRole as _EmployeeRole, HolidayRequest as _HolidayRequest, HolidayRequestId as _HolidayRequestId, HolidayRequestStatus as _HolidayRequestStatus, ManagerNote as _ManagerNote, ManagerNoteId as _ManagerNoteId, ManagerNoteType as _ManagerNoteType, NominationWinner as _NominationWinner, RecordId as _RecordId, Resource as _Resource, ResourceCategory as _ResourceCategory, ResourceId as _ResourceId, ShiftId as _ShiftId, ShiftNote as _ShiftNote, TrainingRecord as _TrainingRecord, TrainingStatus as _TrainingStatus, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAppraisalRecord(arg0: AppraisalRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAppraisalRecord(to_candid_AppraisalRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAppraisalRecord(to_candid_AppraisalRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDocument(arg0: Document): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(to_candid_Document_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(to_candid_Document_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addEmployee(arg0: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(to_candid_Employee_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(to_candid_Employee_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addManagerNote(arg0: ManagerNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addManagerNote(to_candid_ManagerNote_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addManagerNote(to_candid_ManagerNote_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addResource(arg0: Resource): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(to_candid_Resource_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(to_candid_Resource_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addShift(arg0: Shift): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShift(arg0);
            return result;
        }
    }
    async addShiftNote(arg0: ShiftNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addShiftNote(to_candid_ShiftNote_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShiftNote(to_candid_ShiftNote_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSicknessRecord(arg0: SicknessRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSicknessRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSicknessRecord(arg0);
            return result;
        }
    }
    async addTrainingRecord(arg0: TrainingRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrainingRecord(to_candid_TrainingRecord_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrainingRecord(to_candid_TrainingRecord_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteDocument(arg0: DocumentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteManagerNote(arg0: ManagerNoteId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteManagerNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteManagerNote(arg0);
            return result;
        }
    }
    async deleteResource(arg0: ResourceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResource(arg0);
            return result;
        }
    }
    async deleteShift(arg0: ShiftId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShift(arg0);
            return result;
        }
    }
    async getAllDocuments(): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDocuments();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDocuments();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHolidayRequests(): Promise<Array<HolidayRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHolidayRequests();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHolidayRequests();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllShifts(): Promise<Array<Shift>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShifts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShifts();
            return result;
        }
    }
    async getAppraisalsByEmployee(arg0: EmployeeId): Promise<Array<AppraisalRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppraisalsByEmployee(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppraisalsByEmployee(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: EmployeeId): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHolidayRequestsByEmployee(arg0: EmployeeId): Promise<Array<HolidayRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHolidayRequestsByEmployee(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHolidayRequestsByEmployee(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getManagerNotesByEmployee(arg0: EmployeeId): Promise<Array<ManagerNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getManagerNotesByEmployee(arg0);
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManagerNotesByEmployee(arg0);
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNominationsByMonth(arg0: string): Promise<Array<Nomination>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNominationsByMonth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNominationsByMonth(arg0);
            return result;
        }
    }
    async getResources(arg0: ResourceCategory | null): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResources(to_candid_opt_n69(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResources(to_candid_opt_n69(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShiftNotesByShift(arg0: ShiftId): Promise<Array<ShiftNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShiftNotesByShift(arg0);
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShiftNotesByShift(arg0);
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShiftsByEmployee(arg0: EmployeeId): Promise<Array<Shift>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShiftsByEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShiftsByEmployee(arg0);
            return result;
        }
    }
    async getSicknessRecordsByEmployee(arg0: EmployeeId): Promise<Array<SicknessRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSicknessRecordsByEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSicknessRecordsByEmployee(arg0);
            return result;
        }
    }
    async getTrainingRecordsByEmployee(arg0: EmployeeId): Promise<Array<TrainingRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingRecordsByEmployee(arg0);
                return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingRecordsByEmployee(arg0);
            return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWinnerByMonth(arg0: string): Promise<NominationWinner | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWinnerByMonth(arg0);
                return from_candid_opt_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWinnerByMonth(arg0);
            return from_candid_opt_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async markWinnerBonus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWinnerBonus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWinnerBonus(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n90(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n90(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n92(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n92(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setMonthWinner(arg0: string, arg1: EmployeeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMonthWinner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMonthWinner(arg0, arg1);
            return result;
        }
    }
    async submitHolidayRequest(arg0: HolidayRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitHolidayRequest(to_candid_HolidayRequest_n94(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitHolidayRequest(to_candid_HolidayRequest_n94(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitNomination(arg0: Nomination): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitNomination(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitNomination(arg0);
            return result;
        }
    }
    async updateAppraisalRecord(arg0: AppraisalRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppraisalRecord(to_candid_AppraisalRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppraisalRecord(to_candid_AppraisalRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDocument(arg0: Document): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDocument(to_candid_Document_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDocument(to_candid_Document_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEmployee(arg0: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(to_candid_Employee_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(to_candid_Employee_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateHolidayRequestStatus(arg0: HolidayRequestId, arg1: HolidayRequestStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHolidayRequestStatus(arg0, to_candid_HolidayRequestStatus_n96(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHolidayRequestStatus(arg0, to_candid_HolidayRequestStatus_n96(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateManagerNote(arg0: ManagerNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateManagerNote(to_candid_ManagerNote_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateManagerNote(to_candid_ManagerNote_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateResource(arg0: Resource): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResource(to_candid_Resource_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResource(to_candid_Resource_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateShift(arg0: Shift): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShift(arg0);
            return result;
        }
    }
    async updateTrainingRecord(arg0: TrainingRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrainingRecord(to_candid_TrainingRecord_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrainingRecord(to_candid_TrainingRecord_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AppraisalRecord_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppraisalRecord): AppraisalRecord {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_AppraisalType_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppraisalType): AppraisalType {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n89(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentCategory_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentCategory): DocumentCategory {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Document_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeRole): EmployeeRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_HolidayRequestStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HolidayRequestStatus): HolidayRequestStatus {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_HolidayRequest_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HolidayRequest): HolidayRequest {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ManagerNoteType_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManagerNoteType): ManagerNoteType {
    return from_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function from_candid_ManagerNote_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManagerNote): ManagerNote {
    return from_candid_record_n66(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceCategory_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceCategory): ResourceCategory {
    return from_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function from_candid_Resource_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Resource {
    return from_candid_record_n72(_uploadFile, _downloadFile, value);
}
function from_candid_ShiftNote_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShiftNote): ShiftNote {
    return from_candid_record_n77(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingRecord_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingRecord): TrainingRecord {
    return from_candid_record_n80(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingStatus_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingStatus): TrainingStatus {
    return from_candid_variant_n82(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n87(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n58(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployeeId]): EmployeeId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : from_candid_Employee_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NominationWinner]): NominationWinner | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DocumentId;
    title: string;
    content: [] | [string];
    description: string;
    isVisible: boolean;
    category: _DocumentCategory;
    uploadedAt: bigint;
    fileUrl: [] | [string];
}): {
    id: DocumentId;
    title: string;
    content?: string;
    description: string;
    isVisible: boolean;
    category: DocumentCategory;
    uploadedAt: bigint;
    fileUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.content)),
        description: value.description,
        isVisible: value.isVisible,
        category: from_candid_DocumentCategory_n40(_uploadFile, _downloadFile, value.category),
        uploadedAt: value.uploadedAt,
        fileUrl: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.fileUrl))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EmployeeId;
    role: _EmployeeRole;
    fullName: string;
    isActive: boolean;
    email: string;
    jobTitle: string;
    phone: string;
    department: string;
    startDate: bigint;
    accountLevel: _EmployeeRole;
}): {
    id: EmployeeId;
    role: EmployeeRole;
    fullName: string;
    isActive: boolean;
    email: string;
    jobTitle: string;
    phone: string;
    department: string;
    startDate: bigint;
    accountLevel: EmployeeRole;
} {
    return {
        id: value.id,
        role: from_candid_EmployeeRole_n45(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        isActive: value.isActive,
        email: value.email,
        jobTitle: value.jobTitle,
        phone: value.phone,
        department: value.department,
        startDate: value.startDate,
        accountLevel: from_candid_EmployeeRole_n45(_uploadFile, _downloadFile, value.accountLevel)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _HolidayRequestId;
    status: _HolidayRequestStatus;
    endDate: bigint;
    createdAt: bigint;
    employeeId: _EmployeeId;
    startDate: bigint;
    reason: [] | [string];
}): {
    id: HolidayRequestId;
    status: HolidayRequestStatus;
    endDate: bigint;
    createdAt: bigint;
    employeeId: EmployeeId;
    startDate: bigint;
    reason?: string;
} {
    return {
        id: value.id,
        status: from_candid_HolidayRequestStatus_n50(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        createdAt: value.createdAt,
        employeeId: value.employeeId,
        startDate: value.startDate,
        reason: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.reason))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    scheduledDate: bigint;
    appraisalType: _AppraisalType;
    employeeId: _EmployeeId;
    notes: string;
    isComplete: boolean;
}): {
    id: RecordId;
    scheduledDate: bigint;
    appraisalType: AppraisalType;
    employeeId: EmployeeId;
    notes: string;
    isComplete: boolean;
} {
    return {
        id: value.id,
        scheduledDate: value.scheduledDate,
        appraisalType: from_candid_AppraisalType_n55(_uploadFile, _downloadFile, value.appraisalType),
        employeeId: value.employeeId,
        notes: value.notes,
        isComplete: value.isComplete
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    employeeId: [] | [_EmployeeId];
}): {
    name: string;
    employeeId?: EmployeeId;
} {
    return {
        name: value.name,
        employeeId: record_opt_to_undefined(from_candid_opt_n60(_uploadFile, _downloadFile, value.employeeId))
    };
}
function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ManagerNoteId;
    content: string;
    createdAt: bigint;
    noteType: _ManagerNoteType;
    authorEmployeeId: _EmployeeId;
    employeeId: _EmployeeId;
}): {
    id: ManagerNoteId;
    content: string;
    createdAt: bigint;
    noteType: ManagerNoteType;
    authorEmployeeId: EmployeeId;
    employeeId: EmployeeId;
} {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        noteType: from_candid_ManagerNoteType_n67(_uploadFile, _downloadFile, value.noteType),
        authorEmployeeId: value.authorEmployeeId,
        employeeId: value.employeeId
    };
}
function from_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ResourceId;
    title: string;
    content: string;
    createdAt: bigint;
    isRestricted: boolean;
    category: _ResourceCategory;
}): {
    id: ResourceId;
    title: string;
    content: string;
    createdAt: bigint;
    isRestricted: boolean;
    category: ResourceCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        isRestricted: value.isRestricted,
        category: from_candid_ResourceCategory_n73(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    noteText: string;
    employeeId: [] | [_EmployeeId];
    createdTimestamp: bigint;
    shiftId: _ShiftId;
}): {
    id: RecordId;
    noteText: string;
    employeeId?: EmployeeId;
    createdTimestamp: bigint;
    shiftId: ShiftId;
} {
    return {
        id: value.id,
        noteText: value.noteText,
        employeeId: record_opt_to_undefined(from_candid_opt_n60(_uploadFile, _downloadFile, value.employeeId)),
        createdTimestamp: value.createdTimestamp,
        shiftId: value.shiftId
    };
}
function from_candid_record_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    status: _TrainingStatus;
    title: string;
    completionDate: [] | [bigint];
    expiryDate: [] | [bigint];
    description: string;
    employeeId: _EmployeeId;
}): {
    id: RecordId;
    status: TrainingStatus;
    title: string;
    completionDate?: bigint;
    expiryDate?: bigint;
    description: string;
    employeeId: EmployeeId;
} {
    return {
        id: value.id,
        status: from_candid_TrainingStatus_n81(_uploadFile, _downloadFile, value.status),
        title: value.title,
        completionDate: record_opt_to_undefined(from_candid_opt_n83(_uploadFile, _downloadFile, value.completionDate)),
        expiryDate: record_opt_to_undefined(from_candid_opt_n83(_uploadFile, _downloadFile, value.expiryDate)),
        description: value.description,
        employeeId: value.employeeId
    };
}
function from_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n88(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    form: null;
} | {
    handbook: null;
} | {
    policy: null;
}): DocumentCategory {
    return "other" in value ? DocumentCategory.other : "form" in value ? DocumentCategory.form : "handbook" in value ? DocumentCategory.handbook : "policy" in value ? DocumentCategory.policy : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    employee: null;
}): EmployeeRole {
    return "manager" in value ? EmployeeRole.manager : "admin" in value ? EmployeeRole.admin : "employee" in value ? EmployeeRole.employee : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    declined: null;
}): HolidayRequestStatus {
    return "pending" in value ? HolidayRequestStatus.pending : "approved" in value ? HolidayRequestStatus.approved : "declined" in value ? HolidayRequestStatus.declined : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    annual: null;
} | {
    midYear: null;
} | {
    probationary: null;
}): AppraisalType {
    return "annual" in value ? AppraisalType.annual : "midYear" in value ? AppraisalType.midYear : "probationary" in value ? AppraisalType.probationary : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    concern: null;
} | {
    sickness: null;
} | {
    performance: null;
} | {
    general: null;
}): ManagerNoteType {
    return "concern" in value ? ManagerNoteType.concern : "sickness" in value ? ManagerNoteType.sickness : "performance" in value ? ManagerNoteType.performance : "general" in value ? ManagerNoteType.general : value;
}
function from_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forms: null;
} | {
    other: null;
} | {
    logins: null;
} | {
    prices: null;
}): ResourceCategory {
    return "forms" in value ? ResourceCategory.forms : "other" in value ? ResourceCategory.other : "logins" in value ? ResourceCategory.logins : "prices" in value ? ResourceCategory.prices : value;
}
function from_candid_variant_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TrainingStatus {
    return "pending" in value ? TrainingStatus.pending : "completed" in value ? TrainingStatus.completed : "inProgress" in value ? TrainingStatus.inProgress : value;
}
function from_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HolidayRequest>): Array<HolidayRequest> {
    return value.map((x)=>from_candid_HolidayRequest_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppraisalRecord>): Array<AppraisalRecord> {
    return value.map((x)=>from_candid_AppraisalRecord_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ManagerNote>): Array<ManagerNote> {
    return value.map((x)=>from_candid_ManagerNote_n65(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Array<Resource> {
    return value.map((x)=>from_candid_Resource_n71(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShiftNote>): Array<ShiftNote> {
    return value.map((x)=>from_candid_ShiftNote_n76(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrainingRecord>): Array<TrainingRecord> {
    return value.map((x)=>from_candid_TrainingRecord_n79(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n86(_uploadFile, _downloadFile, x));
}
function to_candid_AppraisalRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppraisalRecord): _AppraisalRecord {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_AppraisalType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppraisalType): _AppraisalType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n93(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentCategory): _DocumentCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Document_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Document): _Document {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): _EmployeeRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Employee_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_HolidayRequestStatus_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HolidayRequestStatus): _HolidayRequestStatus {
    return to_candid_variant_n97(_uploadFile, _downloadFile, value);
}
function to_candid_HolidayRequest_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HolidayRequest): _HolidayRequest {
    return to_candid_record_n95(_uploadFile, _downloadFile, value);
}
function to_candid_ManagerNoteType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ManagerNoteType): _ManagerNoteType {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_ManagerNote_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ManagerNote): _ManagerNote {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): _ResourceCategory {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_Resource_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Resource): _Resource {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_ShiftNote_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShiftNote): _ShiftNote {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_TrainingRecord_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingRecord): _TrainingRecord {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_TrainingStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingStatus): _TrainingStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n91(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory | null): [] | [_ResourceCategory] {
    return value === null ? candid_none() : candid_some(to_candid_ResourceCategory_n26(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: DocumentId;
    title: string;
    content?: string;
    description: string;
    isVisible: boolean;
    category: DocumentCategory;
    uploadedAt: bigint;
    fileUrl?: string;
}): {
    id: _DocumentId;
    title: string;
    content: [] | [string];
    description: string;
    isVisible: boolean;
    category: _DocumentCategory;
    uploadedAt: bigint;
    fileUrl: [] | [string];
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content ? candid_some(value.content) : candid_none(),
        description: value.description,
        isVisible: value.isVisible,
        category: to_candid_DocumentCategory_n14(_uploadFile, _downloadFile, value.category),
        uploadedAt: value.uploadedAt,
        fileUrl: value.fileUrl ? candid_some(value.fileUrl) : candid_none()
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EmployeeId;
    role: EmployeeRole;
    fullName: string;
    isActive: boolean;
    email: string;
    jobTitle: string;
    phone: string;
    department: string;
    startDate: bigint;
    accountLevel: EmployeeRole;
}): {
    id: _EmployeeId;
    role: _EmployeeRole;
    fullName: string;
    isActive: boolean;
    email: string;
    jobTitle: string;
    phone: string;
    department: string;
    startDate: bigint;
    accountLevel: _EmployeeRole;
} {
    return {
        id: value.id,
        role: to_candid_EmployeeRole_n18(_uploadFile, _downloadFile, value.role),
        fullName: value.fullName,
        isActive: value.isActive,
        email: value.email,
        jobTitle: value.jobTitle,
        phone: value.phone,
        department: value.department,
        startDate: value.startDate,
        accountLevel: to_candid_EmployeeRole_n18(_uploadFile, _downloadFile, value.accountLevel)
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ManagerNoteId;
    content: string;
    createdAt: bigint;
    noteType: ManagerNoteType;
    authorEmployeeId: EmployeeId;
    employeeId: EmployeeId;
}): {
    id: _ManagerNoteId;
    content: string;
    createdAt: bigint;
    noteType: _ManagerNoteType;
    authorEmployeeId: _EmployeeId;
    employeeId: _EmployeeId;
} {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        noteType: to_candid_ManagerNoteType_n22(_uploadFile, _downloadFile, value.noteType),
        authorEmployeeId: value.authorEmployeeId,
        employeeId: value.employeeId
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ResourceId;
    title: string;
    content: string;
    createdAt: bigint;
    isRestricted: boolean;
    category: ResourceCategory;
}): {
    id: _ResourceId;
    title: string;
    content: string;
    createdAt: bigint;
    isRestricted: boolean;
    category: _ResourceCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        isRestricted: value.isRestricted,
        category: to_candid_ResourceCategory_n26(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RecordId;
    noteText: string;
    employeeId?: EmployeeId;
    createdTimestamp: bigint;
    shiftId: ShiftId;
}): {
    id: _RecordId;
    noteText: string;
    employeeId: [] | [_EmployeeId];
    createdTimestamp: bigint;
    shiftId: _ShiftId;
} {
    return {
        id: value.id,
        noteText: value.noteText,
        employeeId: value.employeeId ? candid_some(value.employeeId) : candid_none(),
        createdTimestamp: value.createdTimestamp,
        shiftId: value.shiftId
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RecordId;
    status: TrainingStatus;
    title: string;
    completionDate?: bigint;
    expiryDate?: bigint;
    description: string;
    employeeId: EmployeeId;
}): {
    id: _RecordId;
    status: _TrainingStatus;
    title: string;
    completionDate: [] | [bigint];
    expiryDate: [] | [bigint];
    description: string;
    employeeId: _EmployeeId;
} {
    return {
        id: value.id,
        status: to_candid_TrainingStatus_n32(_uploadFile, _downloadFile, value.status),
        title: value.title,
        completionDate: value.completionDate ? candid_some(value.completionDate) : candid_none(),
        expiryDate: value.expiryDate ? candid_some(value.expiryDate) : candid_none(),
        description: value.description,
        employeeId: value.employeeId
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: RecordId;
    scheduledDate: bigint;
    appraisalType: AppraisalType;
    employeeId: EmployeeId;
    notes: string;
    isComplete: boolean;
}): {
    id: _RecordId;
    scheduledDate: bigint;
    appraisalType: _AppraisalType;
    employeeId: _EmployeeId;
    notes: string;
    isComplete: boolean;
} {
    return {
        id: value.id,
        scheduledDate: value.scheduledDate,
        appraisalType: to_candid_AppraisalType_n10(_uploadFile, _downloadFile, value.appraisalType),
        employeeId: value.employeeId,
        notes: value.notes,
        isComplete: value.isComplete
    };
}
function to_candid_record_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    employeeId?: EmployeeId;
}): {
    name: string;
    employeeId: [] | [_EmployeeId];
} {
    return {
        name: value.name,
        employeeId: value.employeeId ? candid_some(value.employeeId) : candid_none()
    };
}
function to_candid_record_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: HolidayRequestId;
    status: HolidayRequestStatus;
    endDate: bigint;
    createdAt: bigint;
    employeeId: EmployeeId;
    startDate: bigint;
    reason?: string;
}): {
    id: _HolidayRequestId;
    status: _HolidayRequestStatus;
    endDate: bigint;
    createdAt: bigint;
    employeeId: _EmployeeId;
    startDate: bigint;
    reason: [] | [string];
} {
    return {
        id: value.id,
        status: to_candid_HolidayRequestStatus_n96(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        createdAt: value.createdAt,
        employeeId: value.employeeId,
        startDate: value.startDate,
        reason: value.reason ? candid_some(value.reason) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppraisalType): {
    annual: null;
} | {
    midYear: null;
} | {
    probationary: null;
} {
    return value == AppraisalType.annual ? {
        annual: null
    } : value == AppraisalType.midYear ? {
        midYear: null
    } : value == AppraisalType.probationary ? {
        probationary: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentCategory): {
    other: null;
} | {
    form: null;
} | {
    handbook: null;
} | {
    policy: null;
} {
    return value == DocumentCategory.other ? {
        other: null
    } : value == DocumentCategory.form ? {
        form: null
    } : value == DocumentCategory.handbook ? {
        handbook: null
    } : value == DocumentCategory.policy ? {
        policy: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRole): {
    manager: null;
} | {
    admin: null;
} | {
    employee: null;
} {
    return value == EmployeeRole.manager ? {
        manager: null
    } : value == EmployeeRole.admin ? {
        admin: null
    } : value == EmployeeRole.employee ? {
        employee: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ManagerNoteType): {
    concern: null;
} | {
    sickness: null;
} | {
    performance: null;
} | {
    general: null;
} {
    return value == ManagerNoteType.concern ? {
        concern: null
    } : value == ManagerNoteType.sickness ? {
        sickness: null
    } : value == ManagerNoteType.performance ? {
        performance: null
    } : value == ManagerNoteType.general ? {
        general: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): {
    forms: null;
} | {
    other: null;
} | {
    logins: null;
} | {
    prices: null;
} {
    return value == ResourceCategory.forms ? {
        forms: null
    } : value == ResourceCategory.other ? {
        other: null
    } : value == ResourceCategory.logins ? {
        logins: null
    } : value == ResourceCategory.prices ? {
        prices: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrainingStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == TrainingStatus.pending ? {
        pending: null
    } : value == TrainingStatus.completed ? {
        completed: null
    } : value == TrainingStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HolidayRequestStatus): {
    pending: null;
} | {
    approved: null;
} | {
    declined: null;
} {
    return value == HolidayRequestStatus.pending ? {
        pending: null
    } : value == HolidayRequestStatus.approved ? {
        approved: null
    } : value == HolidayRequestStatus.declined ? {
        declined: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
