/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppraisalRecord {
  'id' : RecordId,
  'scheduledDate' : bigint,
  'appraisalType' : AppraisalType,
  'employeeId' : EmployeeId,
  'notes' : string,
  'isComplete' : boolean,
}
export type AppraisalType = { 'annual' : null } |
  { 'midYear' : null } |
  { 'probationary' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Badge {
  'id' : BadgeId,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
  'iconKey' : string,
}
export type BadgeId = string;
export type CategoryId = string;
export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface Document {
  'id' : DocumentId,
  'title' : string,
  'content' : [] | [string],
  'description' : string,
  'isVisible' : boolean,
  'category' : DocumentCategory,
  'uploadedAt' : bigint,
  'fileUrl' : [] | [string],
}
export type DocumentCategory = { 'other' : null } |
  { 'form' : null } |
  { 'handbook' : null } |
  { 'policy' : null };
export type DocumentId = string;
export interface Employee {
  'id' : EmployeeId,
  'role' : EmployeeRole,
  'fullName' : string,
  'isActive' : boolean,
  'email' : string,
  'jobTitle' : string,
  'phone' : string,
  'department' : string,
  'startDate' : bigint,
  'accountLevel' : EmployeeRole,
}
export type EmployeeId = string;
export interface EmployeeOfTheMonthNomination {
  'id' : string,
  'submitterName' : [] | [string],
  'nomineeEmployeeId' : EmployeeId,
  'submitterPrincipal' : [] | [Principal],
  'comment' : string,
  'timestamp' : bigint,
}
export type EmployeeRole = { 'manager' : null } |
  { 'admin' : null } |
  { 'employee' : null };
export interface HolidayRequest {
  'id' : HolidayRequestId,
  'status' : HolidayRequestStatus,
  'endDate' : bigint,
  'createdAt' : bigint,
  'employeeId' : EmployeeId,
  'startDate' : bigint,
  'reason' : [] | [string],
}
export type HolidayRequestId = string;
export type HolidayRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export interface InventoryCategory {
  'categoryId' : CategoryId,
  'name' : string,
  'description' : string,
}
export interface InventoryItem {
  'categoryId' : CategoryId,
  'itemId' : InventoryItemId,
  'lastStocktakeBy' : [] | [string],
  'expectedDeliveryDate' : [] | [bigint],
  'orderStatus' : OrderStatus,
  'supplier' : string,
  'expiryDate' : [] | [bigint],
  'name' : string,
  'size' : [] | [string],
  'currentStockCount' : bigint,
  'lastStocktakeDate' : [] | [bigint],
  'minimumStockLevel' : bigint,
  'price' : [] | [number],
  'orderFrequency' : string,
}
export type InventoryItemId = string;
export interface ManagerNote {
  'id' : ManagerNoteId,
  'content' : string,
  'createdAt' : bigint,
  'noteType' : ManagerNoteType,
  'authorEmployeeId' : EmployeeId,
  'employeeId' : EmployeeId,
}
export type ManagerNoteId = string;
export type ManagerNoteType = { 'concern' : null } |
  { 'sickness' : null } |
  { 'performance' : null } |
  { 'general' : null };
export interface Nomination {
  'id' : NominationId,
  'month' : string,
  'nomineeEmployeeId' : EmployeeId,
  'submittedAt' : bigint,
  'nominatorEmployeeId' : EmployeeId,
  'reason' : string,
}
export type NominationId = string;
export interface NominationWinner {
  'month' : string,
  'hasReceivedBonus' : boolean,
  'employeeId' : EmployeeId,
}
export type OrderStatus = { 'ok' : null } |
  { 'orderRequired' : null } |
  { 'ordered' : null };
export type RecordId = string;
export type Recurrence = { 'none' : null } |
  { 'weekly' : DayOfWeek };
export interface Resource {
  'id' : ResourceId,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'isRestricted' : boolean,
  'category' : ResourceCategory,
}
export type ResourceCategory = { 'forms' : null } |
  { 'other' : null } |
  { 'logins' : null } |
  { 'prices' : null };
export type ResourceId = string;
export interface Shift {
  'id' : ShiftId,
  'startTime' : bigint,
  'endTime' : bigint,
  'date' : bigint,
  'department' : string,
  'assignedEmployees' : Array<EmployeeId>,
}
export type ShiftId = string;
export interface ShiftNote {
  'id' : RecordId,
  'noteText' : string,
  'employeeId' : [] | [EmployeeId],
  'createdTimestamp' : bigint,
  'shiftId' : ShiftId,
}
export interface SicknessRecord {
  'id' : RecordId,
  'absenceStartDate' : bigint,
  'absenceEndDate' : bigint,
  'employeeId' : EmployeeId,
  'returnNote' : string,
  'reason' : string,
}
export interface StaffBadge {
  'id' : StaffBadgeId,
  'assignedAt' : bigint,
  'assignedBy' : EmployeeId,
  'note' : [] | [string],
  'badgeId' : BadgeId,
  'employeeId' : EmployeeId,
}
export type StaffBadgeId = string;
export interface StockRequest {
  'id' : StockRequestId,
  'status' : StockRequestStatus,
  'submitterName' : string,
  'experience' : string,
  'notes' : string,
  'createdTimestamp' : bigint,
  'itemName' : string,
  'quantity' : bigint,
  'deliveredTimestamp' : [] | [bigint],
}
export type StockRequestId = bigint;
export type StockRequestStatus = { 'requested' : null } |
  { 'ordered' : null } |
  { 'delivered' : null } |
  { 'archived' : null };
export type TaskAssignee = { 'everyone' : null } |
  { 'employee' : EmployeeId };
export type TaskId = string;
export interface ToDoTask {
  'id' : TaskId,
  'durationMins' : bigint,
  'completedBy' : [] | [Principal],
  'assignee' : TaskAssignee,
  'title' : string,
  'creator' : Principal,
  'date' : [] | [bigint],
  'description' : string,
  'recurrence' : Recurrence,
  'completedTimestamp' : [] | [bigint],
  'createdTimestamp' : bigint,
}
export interface TrainingRecord {
  'id' : RecordId,
  'status' : TrainingStatus,
  'title' : string,
  'completionDate' : [] | [bigint],
  'expiryDate' : [] | [bigint],
  'description' : string,
  'employeeId' : EmployeeId,
}
export type TrainingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'employeeId' : [] | [EmployeeId],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAppraisalRecord' : ActorMethod<[AppraisalRecord], undefined>,
  'addBadge' : ActorMethod<[Badge], undefined>,
  'addCategory' : ActorMethod<[InventoryCategory], undefined>,
  'addDocument' : ActorMethod<[Document], undefined>,
  'addEmployee' : ActorMethod<[Employee], undefined>,
  'addItem' : ActorMethod<[InventoryItem], undefined>,
  'addManagerNote' : ActorMethod<[ManagerNote], undefined>,
  'addResource' : ActorMethod<[Resource], undefined>,
  'addShift' : ActorMethod<[Shift], undefined>,
  'addShiftNote' : ActorMethod<[ShiftNote], undefined>,
  'addSicknessRecord' : ActorMethod<[SicknessRecord], undefined>,
  'addTrainingRecord' : ActorMethod<[TrainingRecord], undefined>,
  'archiveOldDeliveredRequests' : ActorMethod<[], undefined>,
  'assignBadgeToStaff' : ActorMethod<[StaffBadge], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStockRequest' : ActorMethod<
    [string, string, bigint, string, string],
    StockRequestId
  >,
  'createTask' : ActorMethod<[ToDoTask], undefined>,
  'deleteDocument' : ActorMethod<[DocumentId], undefined>,
  'deleteItem' : ActorMethod<[InventoryItemId], undefined>,
  'deleteManagerNote' : ActorMethod<[ManagerNoteId], undefined>,
  'deleteResource' : ActorMethod<[ResourceId], undefined>,
  'deleteShift' : ActorMethod<[ShiftId], undefined>,
  'deleteTrainingRecord' : ActorMethod<[RecordId], undefined>,
  'getAllCategories' : ActorMethod<[], Array<InventoryCategory>>,
  'getAllDocuments' : ActorMethod<[], Array<Document>>,
  'getAllEmployeeOfTheMonthNominations' : ActorMethod<
    [],
    Array<EmployeeOfTheMonthNomination>
  >,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllHolidayRequests' : ActorMethod<[], Array<HolidayRequest>>,
  'getAllItems' : ActorMethod<[], Array<InventoryItem>>,
  'getAllShifts' : ActorMethod<[], Array<Shift>>,
  'getAppraisalsByEmployee' : ActorMethod<[EmployeeId], Array<AppraisalRecord>>,
  'getBadges' : ActorMethod<[], Array<Badge>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[EmployeeId], [] | [Employee]>,
  'getEmployeeOfTheMonthNominationsByEmployee' : ActorMethod<
    [EmployeeId],
    Array<EmployeeOfTheMonthNomination>
  >,
  'getHolidayRequestsByEmployee' : ActorMethod<
    [EmployeeId],
    Array<HolidayRequest>
  >,
  'getItemsByCategory' : ActorMethod<[CategoryId], Array<InventoryItem>>,
  'getManagerNotesByEmployee' : ActorMethod<[EmployeeId], Array<ManagerNote>>,
  'getNominationsByMonth' : ActorMethod<[string], Array<Nomination>>,
  'getResources' : ActorMethod<[[] | [ResourceCategory]], Array<Resource>>,
  'getShiftNotesByShift' : ActorMethod<[ShiftId], Array<ShiftNote>>,
  'getShiftsByEmployee' : ActorMethod<[EmployeeId], Array<Shift>>,
  'getSicknessRecordsByEmployee' : ActorMethod<
    [EmployeeId],
    Array<SicknessRecord>
  >,
  'getStaffBadges' : ActorMethod<[EmployeeId], Array<StaffBadge>>,
  'getStockRequestById' : ActorMethod<[StockRequestId], [] | [StockRequest]>,
  'getStockRequestsByStatus' : ActorMethod<
    [StockRequestStatus],
    Array<StockRequest>
  >,
  'getTasks' : ActorMethod<[], Array<ToDoTask>>,
  'getTasksForToday' : ActorMethod<[DayOfWeek], Array<ToDoTask>>,
  'getTrainingRecordsByEmployee' : ActorMethod<
    [EmployeeId],
    Array<TrainingRecord>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWinnerByMonth' : ActorMethod<[string], [] | [NominationWinner]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markAdminLoggedInSuccessfully' : ActorMethod<[], boolean>,
  'markTaskComplete' : ActorMethod<[TaskId], undefined>,
  'markWinnerBonus' : ActorMethod<[string], undefined>,
  'removeBadgeFromStaff' : ActorMethod<[StaffBadgeId], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setMonthWinner' : ActorMethod<[string, EmployeeId], undefined>,
  'submitEmployeeOfTheMonthNomination' : ActorMethod<
    [EmployeeId, string, [] | [string]],
    string
  >,
  'submitHolidayRequest' : ActorMethod<[HolidayRequest], undefined>,
  'submitNomination' : ActorMethod<[Nomination], undefined>,
  'updateAppraisalRecord' : ActorMethod<[AppraisalRecord], undefined>,
  'updateDocument' : ActorMethod<[Document], undefined>,
  'updateEmployee' : ActorMethod<[Employee], undefined>,
  'updateHolidayRequestStatus' : ActorMethod<
    [HolidayRequestId, HolidayRequestStatus],
    undefined
  >,
  'updateItem' : ActorMethod<[InventoryItem], undefined>,
  'updateManagerNote' : ActorMethod<[ManagerNote], undefined>,
  'updateResource' : ActorMethod<[Resource], undefined>,
  'updateShift' : ActorMethod<[Shift], undefined>,
  'updateStockRequestStatus' : ActorMethod<
    [StockRequestId, StockRequestStatus],
    undefined
  >,
  'updateTrainingRecord' : ActorMethod<[TrainingRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];