/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const RecordId = IDL.Text;
export const AppraisalType = IDL.Variant({
  'annual' : IDL.Null,
  'midYear' : IDL.Null,
  'probationary' : IDL.Null,
});
export const EmployeeId = IDL.Text;
export const AppraisalRecord = IDL.Record({
  'id' : RecordId,
  'scheduledDate' : IDL.Int,
  'appraisalType' : AppraisalType,
  'employeeId' : EmployeeId,
  'notes' : IDL.Text,
  'isComplete' : IDL.Bool,
});
export const DocumentId = IDL.Text;
export const DocumentCategory = IDL.Variant({
  'other' : IDL.Null,
  'form' : IDL.Null,
  'handbook' : IDL.Null,
  'policy' : IDL.Null,
});
export const Document = IDL.Record({
  'id' : DocumentId,
  'title' : IDL.Text,
  'content' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'isVisible' : IDL.Bool,
  'category' : DocumentCategory,
  'uploadedAt' : IDL.Int,
  'fileUrl' : IDL.Opt(IDL.Text),
});
export const EmployeeRole = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'employee' : IDL.Null,
});
export const Employee = IDL.Record({
  'id' : EmployeeId,
  'role' : EmployeeRole,
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'jobTitle' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'startDate' : IDL.Int,
  'accountLevel' : EmployeeRole,
});
export const ManagerNoteId = IDL.Text;
export const ManagerNoteType = IDL.Variant({
  'concern' : IDL.Null,
  'sickness' : IDL.Null,
  'performance' : IDL.Null,
  'general' : IDL.Null,
});
export const ManagerNote = IDL.Record({
  'id' : ManagerNoteId,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'noteType' : ManagerNoteType,
  'authorEmployeeId' : EmployeeId,
  'employeeId' : EmployeeId,
});
export const ResourceId = IDL.Text;
export const ResourceCategory = IDL.Variant({
  'forms' : IDL.Null,
  'other' : IDL.Null,
  'logins' : IDL.Null,
  'prices' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : ResourceId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRestricted' : IDL.Bool,
  'category' : ResourceCategory,
});
export const ShiftId = IDL.Text;
export const Shift = IDL.Record({
  'id' : ShiftId,
  'startTime' : IDL.Int,
  'endTime' : IDL.Int,
  'date' : IDL.Int,
  'department' : IDL.Text,
  'assignedEmployees' : IDL.Vec(EmployeeId),
});
export const ShiftNote = IDL.Record({
  'id' : RecordId,
  'noteText' : IDL.Text,
  'employeeId' : IDL.Opt(EmployeeId),
  'createdTimestamp' : IDL.Int,
  'shiftId' : ShiftId,
});
export const SicknessRecord = IDL.Record({
  'id' : RecordId,
  'absenceStartDate' : IDL.Int,
  'absenceEndDate' : IDL.Int,
  'employeeId' : EmployeeId,
  'returnNote' : IDL.Text,
  'reason' : IDL.Text,
});
export const TrainingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TrainingRecord = IDL.Record({
  'id' : RecordId,
  'status' : TrainingStatus,
  'title' : IDL.Text,
  'completionDate' : IDL.Opt(IDL.Int),
  'expiryDate' : IDL.Opt(IDL.Int),
  'description' : IDL.Text,
  'employeeId' : EmployeeId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HolidayRequestId = IDL.Text;
export const HolidayRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const HolidayRequest = IDL.Record({
  'id' : HolidayRequestId,
  'status' : HolidayRequestStatus,
  'endDate' : IDL.Int,
  'createdAt' : IDL.Int,
  'employeeId' : EmployeeId,
  'startDate' : IDL.Int,
  'reason' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Opt(EmployeeId),
});
export const NominationId = IDL.Text;
export const Nomination = IDL.Record({
  'id' : NominationId,
  'month' : IDL.Text,
  'nomineeEmployeeId' : EmployeeId,
  'submittedAt' : IDL.Int,
  'nominatorEmployeeId' : EmployeeId,
  'reason' : IDL.Text,
});
export const NominationWinner = IDL.Record({
  'month' : IDL.Text,
  'hasReceivedBonus' : IDL.Bool,
  'employeeId' : EmployeeId,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAppraisalRecord' : IDL.Func([AppraisalRecord], [], []),
  'addDocument' : IDL.Func([Document], [], []),
  'addEmployee' : IDL.Func([Employee], [], []),
  'addManagerNote' : IDL.Func([ManagerNote], [], []),
  'addResource' : IDL.Func([Resource], [], []),
  'addShift' : IDL.Func([Shift], [], []),
  'addShiftNote' : IDL.Func([ShiftNote], [], []),
  'addSicknessRecord' : IDL.Func([SicknessRecord], [], []),
  'addTrainingRecord' : IDL.Func([TrainingRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDocument' : IDL.Func([DocumentId], [], []),
  'deleteManagerNote' : IDL.Func([ManagerNoteId], [], []),
  'deleteResource' : IDL.Func([ResourceId], [], []),
  'deleteShift' : IDL.Func([ShiftId], [], []),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllHolidayRequests' : IDL.Func([], [IDL.Vec(HolidayRequest)], ['query']),
  'getAllShifts' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
  'getAppraisalsByEmployee' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(AppraisalRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([EmployeeId], [IDL.Opt(Employee)], ['query']),
  'getHolidayRequestsByEmployee' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(HolidayRequest)],
      ['query'],
    ),
  'getManagerNotesByEmployee' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(ManagerNote)],
      ['query'],
    ),
  'getNominationsByMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Nomination)],
      ['query'],
    ),
  'getResources' : IDL.Func(
      [IDL.Opt(ResourceCategory)],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'getShiftNotesByShift' : IDL.Func([ShiftId], [IDL.Vec(ShiftNote)], ['query']),
  'getShiftsByEmployee' : IDL.Func([EmployeeId], [IDL.Vec(Shift)], ['query']),
  'getSicknessRecordsByEmployee' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(SicknessRecord)],
      ['query'],
    ),
  'getTrainingRecordsByEmployee' : IDL.Func(
      [EmployeeId],
      [IDL.Vec(TrainingRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWinnerByMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(NominationWinner)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markWinnerBonus' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setMonthWinner' : IDL.Func([IDL.Text, EmployeeId], [], []),
  'submitHolidayRequest' : IDL.Func([HolidayRequest], [], []),
  'submitNomination' : IDL.Func([Nomination], [], []),
  'updateAppraisalRecord' : IDL.Func([AppraisalRecord], [], []),
  'updateDocument' : IDL.Func([Document], [], []),
  'updateEmployee' : IDL.Func([Employee], [], []),
  'updateHolidayRequestStatus' : IDL.Func(
      [HolidayRequestId, HolidayRequestStatus],
      [],
      [],
    ),
  'updateManagerNote' : IDL.Func([ManagerNote], [], []),
  'updateResource' : IDL.Func([Resource], [], []),
  'updateShift' : IDL.Func([Shift], [], []),
  'updateTrainingRecord' : IDL.Func([TrainingRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const RecordId = IDL.Text;
  const AppraisalType = IDL.Variant({
    'annual' : IDL.Null,
    'midYear' : IDL.Null,
    'probationary' : IDL.Null,
  });
  const EmployeeId = IDL.Text;
  const AppraisalRecord = IDL.Record({
    'id' : RecordId,
    'scheduledDate' : IDL.Int,
    'appraisalType' : AppraisalType,
    'employeeId' : EmployeeId,
    'notes' : IDL.Text,
    'isComplete' : IDL.Bool,
  });
  const DocumentId = IDL.Text;
  const DocumentCategory = IDL.Variant({
    'other' : IDL.Null,
    'form' : IDL.Null,
    'handbook' : IDL.Null,
    'policy' : IDL.Null,
  });
  const Document = IDL.Record({
    'id' : DocumentId,
    'title' : IDL.Text,
    'content' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'isVisible' : IDL.Bool,
    'category' : DocumentCategory,
    'uploadedAt' : IDL.Int,
    'fileUrl' : IDL.Opt(IDL.Text),
  });
  const EmployeeRole = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'employee' : IDL.Null,
  });
  const Employee = IDL.Record({
    'id' : EmployeeId,
    'role' : EmployeeRole,
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'jobTitle' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'startDate' : IDL.Int,
    'accountLevel' : EmployeeRole,
  });
  const ManagerNoteId = IDL.Text;
  const ManagerNoteType = IDL.Variant({
    'concern' : IDL.Null,
    'sickness' : IDL.Null,
    'performance' : IDL.Null,
    'general' : IDL.Null,
  });
  const ManagerNote = IDL.Record({
    'id' : ManagerNoteId,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'noteType' : ManagerNoteType,
    'authorEmployeeId' : EmployeeId,
    'employeeId' : EmployeeId,
  });
  const ResourceId = IDL.Text;
  const ResourceCategory = IDL.Variant({
    'forms' : IDL.Null,
    'other' : IDL.Null,
    'logins' : IDL.Null,
    'prices' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : ResourceId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRestricted' : IDL.Bool,
    'category' : ResourceCategory,
  });
  const ShiftId = IDL.Text;
  const Shift = IDL.Record({
    'id' : ShiftId,
    'startTime' : IDL.Int,
    'endTime' : IDL.Int,
    'date' : IDL.Int,
    'department' : IDL.Text,
    'assignedEmployees' : IDL.Vec(EmployeeId),
  });
  const ShiftNote = IDL.Record({
    'id' : RecordId,
    'noteText' : IDL.Text,
    'employeeId' : IDL.Opt(EmployeeId),
    'createdTimestamp' : IDL.Int,
    'shiftId' : ShiftId,
  });
  const SicknessRecord = IDL.Record({
    'id' : RecordId,
    'absenceStartDate' : IDL.Int,
    'absenceEndDate' : IDL.Int,
    'employeeId' : EmployeeId,
    'returnNote' : IDL.Text,
    'reason' : IDL.Text,
  });
  const TrainingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TrainingRecord = IDL.Record({
    'id' : RecordId,
    'status' : TrainingStatus,
    'title' : IDL.Text,
    'completionDate' : IDL.Opt(IDL.Int),
    'expiryDate' : IDL.Opt(IDL.Int),
    'description' : IDL.Text,
    'employeeId' : EmployeeId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HolidayRequestId = IDL.Text;
  const HolidayRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const HolidayRequest = IDL.Record({
    'id' : HolidayRequestId,
    'status' : HolidayRequestStatus,
    'endDate' : IDL.Int,
    'createdAt' : IDL.Int,
    'employeeId' : EmployeeId,
    'startDate' : IDL.Int,
    'reason' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'employeeId' : IDL.Opt(EmployeeId),
  });
  const NominationId = IDL.Text;
  const Nomination = IDL.Record({
    'id' : NominationId,
    'month' : IDL.Text,
    'nomineeEmployeeId' : EmployeeId,
    'submittedAt' : IDL.Int,
    'nominatorEmployeeId' : EmployeeId,
    'reason' : IDL.Text,
  });
  const NominationWinner = IDL.Record({
    'month' : IDL.Text,
    'hasReceivedBonus' : IDL.Bool,
    'employeeId' : EmployeeId,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAppraisalRecord' : IDL.Func([AppraisalRecord], [], []),
    'addDocument' : IDL.Func([Document], [], []),
    'addEmployee' : IDL.Func([Employee], [], []),
    'addManagerNote' : IDL.Func([ManagerNote], [], []),
    'addResource' : IDL.Func([Resource], [], []),
    'addShift' : IDL.Func([Shift], [], []),
    'addShiftNote' : IDL.Func([ShiftNote], [], []),
    'addSicknessRecord' : IDL.Func([SicknessRecord], [], []),
    'addTrainingRecord' : IDL.Func([TrainingRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDocument' : IDL.Func([DocumentId], [], []),
    'deleteManagerNote' : IDL.Func([ManagerNoteId], [], []),
    'deleteResource' : IDL.Func([ResourceId], [], []),
    'deleteShift' : IDL.Func([ShiftId], [], []),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllHolidayRequests' : IDL.Func(
        [],
        [IDL.Vec(HolidayRequest)],
        ['query'],
      ),
    'getAllShifts' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
    'getAppraisalsByEmployee' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(AppraisalRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([EmployeeId], [IDL.Opt(Employee)], ['query']),
    'getHolidayRequestsByEmployee' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(HolidayRequest)],
        ['query'],
      ),
    'getManagerNotesByEmployee' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(ManagerNote)],
        ['query'],
      ),
    'getNominationsByMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Nomination)],
        ['query'],
      ),
    'getResources' : IDL.Func(
        [IDL.Opt(ResourceCategory)],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'getShiftNotesByShift' : IDL.Func(
        [ShiftId],
        [IDL.Vec(ShiftNote)],
        ['query'],
      ),
    'getShiftsByEmployee' : IDL.Func([EmployeeId], [IDL.Vec(Shift)], ['query']),
    'getSicknessRecordsByEmployee' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(SicknessRecord)],
        ['query'],
      ),
    'getTrainingRecordsByEmployee' : IDL.Func(
        [EmployeeId],
        [IDL.Vec(TrainingRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWinnerByMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(NominationWinner)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markWinnerBonus' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setMonthWinner' : IDL.Func([IDL.Text, EmployeeId], [], []),
    'submitHolidayRequest' : IDL.Func([HolidayRequest], [], []),
    'submitNomination' : IDL.Func([Nomination], [], []),
    'updateAppraisalRecord' : IDL.Func([AppraisalRecord], [], []),
    'updateDocument' : IDL.Func([Document], [], []),
    'updateEmployee' : IDL.Func([Employee], [], []),
    'updateHolidayRequestStatus' : IDL.Func(
        [HolidayRequestId, HolidayRequestStatus],
        [],
        [],
      ),
    'updateManagerNote' : IDL.Func([ManagerNote], [], []),
    'updateResource' : IDL.Func([Resource], [], []),
    'updateShift' : IDL.Func([Shift], [], []),
    'updateTrainingRecord' : IDL.Func([TrainingRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };