/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppraisalRecord {
  'id' : RecordId,
  'scheduledDate' : bigint,
  'appraisalType' : AppraisalType,
  'employeeId' : EmployeeId,
  'notes' : string,
  'isComplete' : boolean,
}
export type AppraisalType = { 'annual' : null } |
  { 'midYear' : null } |
  { 'probationary' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Document {
  'id' : DocumentId,
  'title' : string,
  'content' : [] | [string],
  'description' : string,
  'isVisible' : boolean,
  'category' : DocumentCategory,
  'uploadedAt' : bigint,
  'fileUrl' : [] | [string],
}
export type DocumentCategory = { 'other' : null } |
  { 'form' : null } |
  { 'handbook' : null } |
  { 'policy' : null };
export type DocumentId = string;
export interface Employee {
  'id' : EmployeeId,
  'role' : EmployeeRole,
  'fullName' : string,
  'isActive' : boolean,
  'email' : string,
  'jobTitle' : string,
  'phone' : string,
  'department' : string,
  'startDate' : bigint,
  'accountLevel' : EmployeeRole,
}
export type EmployeeId = string;
export type EmployeeRole = { 'manager' : null } |
  { 'admin' : null } |
  { 'employee' : null };
export interface HolidayRequest {
  'id' : HolidayRequestId,
  'status' : HolidayRequestStatus,
  'endDate' : bigint,
  'createdAt' : bigint,
  'employeeId' : EmployeeId,
  'startDate' : bigint,
  'reason' : [] | [string],
}
export type HolidayRequestId = string;
export type HolidayRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export interface ManagerNote {
  'id' : ManagerNoteId,
  'content' : string,
  'createdAt' : bigint,
  'noteType' : ManagerNoteType,
  'authorEmployeeId' : EmployeeId,
  'employeeId' : EmployeeId,
}
export type ManagerNoteId = string;
export type ManagerNoteType = { 'concern' : null } |
  { 'sickness' : null } |
  { 'performance' : null } |
  { 'general' : null };
export interface Nomination {
  'id' : NominationId,
  'month' : string,
  'nomineeEmployeeId' : EmployeeId,
  'submittedAt' : bigint,
  'nominatorEmployeeId' : EmployeeId,
  'reason' : string,
}
export type NominationId = string;
export interface NominationWinner {
  'month' : string,
  'hasReceivedBonus' : boolean,
  'employeeId' : EmployeeId,
}
export type RecordId = string;
export interface Resource {
  'id' : ResourceId,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'isRestricted' : boolean,
  'category' : ResourceCategory,
}
export type ResourceCategory = { 'forms' : null } |
  { 'other' : null } |
  { 'logins' : null } |
  { 'prices' : null };
export type ResourceId = string;
export interface Shift {
  'id' : ShiftId,
  'startTime' : bigint,
  'endTime' : bigint,
  'date' : bigint,
  'department' : string,
  'assignedEmployees' : Array<EmployeeId>,
}
export type ShiftId = string;
export interface ShiftNote {
  'id' : RecordId,
  'noteText' : string,
  'employeeId' : [] | [EmployeeId],
  'createdTimestamp' : bigint,
  'shiftId' : ShiftId,
}
export interface SicknessRecord {
  'id' : RecordId,
  'absenceStartDate' : bigint,
  'absenceEndDate' : bigint,
  'employeeId' : EmployeeId,
  'returnNote' : string,
  'reason' : string,
}
export interface TrainingRecord {
  'id' : RecordId,
  'status' : TrainingStatus,
  'title' : string,
  'completionDate' : [] | [bigint],
  'expiryDate' : [] | [bigint],
  'description' : string,
  'employeeId' : EmployeeId,
}
export type TrainingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'employeeId' : [] | [EmployeeId],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAppraisalRecord' : ActorMethod<[AppraisalRecord], undefined>,
  'addDocument' : ActorMethod<[Document], undefined>,
  'addEmployee' : ActorMethod<[Employee], undefined>,
  'addManagerNote' : ActorMethod<[ManagerNote], undefined>,
  'addResource' : ActorMethod<[Resource], undefined>,
  'addShift' : ActorMethod<[Shift], undefined>,
  'addShiftNote' : ActorMethod<[ShiftNote], undefined>,
  'addSicknessRecord' : ActorMethod<[SicknessRecord], undefined>,
  'addTrainingRecord' : ActorMethod<[TrainingRecord], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDocument' : ActorMethod<[DocumentId], undefined>,
  'deleteManagerNote' : ActorMethod<[ManagerNoteId], undefined>,
  'deleteResource' : ActorMethod<[ResourceId], undefined>,
  'deleteShift' : ActorMethod<[ShiftId], undefined>,
  'getAllDocuments' : ActorMethod<[], Array<Document>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllHolidayRequests' : ActorMethod<[], Array<HolidayRequest>>,
  'getAllShifts' : ActorMethod<[], Array<Shift>>,
  'getAppraisalsByEmployee' : ActorMethod<[EmployeeId], Array<AppraisalRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[EmployeeId], [] | [Employee]>,
  'getHolidayRequestsByEmployee' : ActorMethod<
    [EmployeeId],
    Array<HolidayRequest>
  >,
  'getManagerNotesByEmployee' : ActorMethod<[EmployeeId], Array<ManagerNote>>,
  'getNominationsByMonth' : ActorMethod<[string], Array<Nomination>>,
  'getResources' : ActorMethod<[[] | [ResourceCategory]], Array<Resource>>,
  'getShiftNotesByShift' : ActorMethod<[ShiftId], Array<ShiftNote>>,
  'getShiftsByEmployee' : ActorMethod<[EmployeeId], Array<Shift>>,
  'getSicknessRecordsByEmployee' : ActorMethod<
    [EmployeeId],
    Array<SicknessRecord>
  >,
  'getTrainingRecordsByEmployee' : ActorMethod<
    [EmployeeId],
    Array<TrainingRecord>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWinnerByMonth' : ActorMethod<[string], [] | [NominationWinner]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'markWinnerBonus' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setMonthWinner' : ActorMethod<[string, EmployeeId], undefined>,
  'submitHolidayRequest' : ActorMethod<[HolidayRequest], undefined>,
  'submitNomination' : ActorMethod<[Nomination], undefined>,
  'updateAppraisalRecord' : ActorMethod<[AppraisalRecord], undefined>,
  'updateDocument' : ActorMethod<[Document], undefined>,
  'updateEmployee' : ActorMethod<[Employee], undefined>,
  'updateHolidayRequestStatus' : ActorMethod<
    [HolidayRequestId, HolidayRequestStatus],
    undefined
  >,
  'updateManagerNote' : ActorMethod<[ManagerNote], undefined>,
  'updateResource' : ActorMethod<[Resource], undefined>,
  'updateShift' : ActorMethod<[Shift], undefined>,
  'updateTrainingRecord' : ActorMethod<[TrainingRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];